### ISSUE TITLE
What's the difference to autoenv?

### ISSUE THREAD

**Issue by ionelmc** [zimbatm/direnv#159]
This is autoenv: https://github.com/kennethreitz/autoenv

What's different?

**Comment by zimbatm** [comment]
The main difference is that autoenv doesn't know how to unload an environment. It means that over time when you `cd` into various projects settings might accumulate, this can lead to situations where one shell in the same folder can execute a command and not the other. I don't have a first hand experience to know if it's a problem or not.

I like autoenv because it's very simple, it's one file: https://github.com/kennethreitz/autoenv/blob/master/activate.sh . That means it's a bit unfair to ask it to do a lot of things. Direnv has more features but is also generally more complex code-wise.

Both have a security mechanism to not load arbitrary code.

autoenv loads `.env` files which are a standard established by the foreman project, direnv loads `.envrc` files which are bash files whose exports are going to be imported in the current shell.

direnv hooks into the shell more nicely. autoenv overrides the `cd` command but other commands such as `pushd` and `popd` can also change directories.

direnv supports bash, zsh, fish and tcsh and vim. it's relatively easy to add support for more shells.

**Comment by ionelmc** [comment]
Ok, direnv use different hooks for sourcing the env vars, does that mean it rolls them back? 

Also, doesn't it mean direnv is slower because it need to spawn 2 additional processes (one for go process, and one for the envrc)?

**Comment by zimbatm** [comment]
yeah, `direnv export` is executed before every prompt (see `direnv hook`) but is fast enough that it's not noticeable. bash is invoked only when a new `.envrc` is detected. the result is then imported into the current shell with also some state in the `DIRENV_*` environment variables. this is then used in the next executions of `direnv export`. All this complexity means that it's easy to re-load environments when the `.envrc` file is changed, or switch/unload environment when going from one project to another.

**Comment by ionelmc** [comment]
How does the env cleanup work?

Mind you, I'm not critiquing the tool, I just want to understand it :)

**Comment by zimbatm** [comment]
When an environment variable gets changed the original version is stored inside of the `DIRENV_DIFF` environment variable. This is what's used to restore the original version.

If you want to get more details into the heuristic, this is where all the magic is happening: https://github.com/zimbatm/direnv/blob/master/cmd_export.go

**Comment by ionelmc** [comment]
Thanks. It would also be useful to have all this info in the readme in an
"Internals" section I think.


Thanks,
-- Ionel Cristian Mărieș, blog.ionelmc.ro

**Comment by zimbatm** [comment]
For now I've made an entry in the wiki: https://github.com/zimbatm/direnv/wiki/Autoenv

Thanks for asking these questions,  it's always interesting to have that kind of conversation to me

**Comment by ssbarnea** [comment]
Keeping a comparison with other tools would be really useful as it would allow people to take the better bet ;)

**Comment by zimbatm** [comment]
I'm also mentioning it in the main README: https://github.com/direnv/direnv/#similar-projects
Is that not enough? I'm happy to point to other projects, I really like it when other projects do that as well.
